/**
 * Telegram Delivery Service
 *
 * Formats and sends weekly analytics reports to a Telegram chat.
 * Uses the Telegram Bot API directly — no extra libraries needed.
 *
 * Message format uses Telegram MarkdownV2 so it renders cleanly
 * in the chat with bold headers and code blocks.
 */

import type { Report, ReportStats, Site } from "@/types";

const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN!;
const TELEGRAM_API = `https://api.telegram.org/bot${BOT_TOKEN}`;

/** Send a formatted analytics report to a Telegram chat */
export async function sendReportToTelegram(
  chatId: string,
  site: Site,
  report: Report
): Promise<void> {
  const text = formatReportMessage(site, report);
  await sendMessage(chatId, text);
}

/** Send an arbitrary message to a Telegram chat */
export async function sendMessage(
  chatId: string,
  text: string,
  parseMode: "MarkdownV2" | "HTML" | "Markdown" = "MarkdownV2"
): Promise<void> {
  const res = await fetch(`${TELEGRAM_API}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      chat_id: chatId,
      text,
      parse_mode: parseMode,
      disable_web_page_preview: true,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Telegram API error: ${res.status} — ${err}`);
  }
}

// ─────────────────────────────────────────────
// Message formatter
// ─────────────────────────────────────────────

function formatReportMessage(site: Site, report: Report): string {
  const stats = report.raw_stats;
  const periodStart = new Date(report.period_start);
  const periodEnd = new Date(report.period_end);
  const period = `${formatDate(periodStart)} – ${formatDate(periodEnd)}`;

  // Build lines — escape special chars for MarkdownV2
  const lines: string[] = [
    `📊 *${esc(site.name)}* Weekly Report`,
    `_${esc(period)}_`,
    ``,
    `*Core Metrics*`,
    `👁 Pageviews: *${n(stats.total_pageviews)}*`,
    `👤 Unique visitors: *${n(stats.unique_visitors)}*`,
    `🔁 Sessions: *${n(stats.sessions)}*`,
    `↩️ Bounce rate: *${stats.bounce_rate.toFixed(1)}%*`,
    `⏱ Avg session: *${formatDuration(stats.avg_session_duration_s)}*`,
    ``,
  ];

  // Top pages
  if (stats.top_pages.length > 0) {
    lines.push(`*Top Pages*`);
    stats.top_pages.slice(0, 5).forEach((p, i) => {
      lines.push(`${i + 1}\\. ${esc(p.url)} — ${n(p.views)} views`);
    });
    lines.push(``);
  }

  // Top traffic sources
  if (stats.top_referrers.length > 0) {
    lines.push(`*Traffic Sources*`);
    stats.top_referrers.slice(0, 5).forEach((r) => {
      lines.push(`• ${esc(r.source)} — ${n(r.visits)} visits`);
    });
    lines.push(``);
  }

  // Top countries
  if (stats.top_countries.length > 0) {
    lines.push(`*Top Countries*`);
    stats.top_countries.slice(0, 3).forEach((c) => {
      lines.push(`• ${esc(c.country)} — ${n(c.visits)} visits`);
    });
    lines.push(``);
  }

  // Custom events
  if (stats.top_events.length > 0) {
    lines.push(`*Custom Events*`);
    stats.top_events.slice(0, 5).forEach((e) => {
      lines.push(`• ${esc(e.name)}: ${n(e.count)}x`);
    });
    lines.push(``);
  }

  // AI Summary
  lines.push(`*📝 AI Summary*`);
  lines.push(esc(report.summary));
  lines.push(``);

  // Growth suggestions
  lines.push(`*💡 Growth Suggestions*`);
  lines.push(esc(report.suggestions));
  lines.push(``);

  lines.push(`_Generated by Brieflytics · ${esc(new Date().toLocaleDateString("en-GB"))}_`);

  return lines.join("\n");
}

// ─────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────

/** Escape special characters for Telegram MarkdownV2 */
function esc(text: string): string {
  return text.replace(/[_*[\]()~`>#+\-=|{}.!\\]/g, "\\$&");
}

/** Format a number with thousands separator */
function n(num: number): string {
  return num.toLocaleString("en-US");
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
  });
}

function formatDuration(seconds: number): string {
  if (seconds < 60) return `${Math.round(seconds)}s`;
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  return `${m}m ${s}s`;
}
